import type { Language } from './motivationalMessages';

export type ExerciseGroup = { categories: Record<Language, string>; exercises: Record<Language, string[]> };

export const exerciseGroups: ExerciseGroup[] = [
  { categories: { en: 'Chest', de: 'Brust', fr: 'Pectoraux', it: 'Petto', es: 'Pecho' }, exercises: { en: ['Bench Press', 'Cable Chest Press', 'Push-Up', 'Pec Deck', 'Chest Press'], de: ['Bankdrücken', 'Kabel-Brustpresse', 'Liegestütz', 'Butterfly', 'Brustpresse'], fr: ['Développé couché', 'Presse poitrine à la poulie', 'Pompes', 'Pec deck', 'Presse poitrine'], it: ['Panca piana', 'Chest press ai cavi', 'Piegamenti', 'Pec deck', 'Chest press'], es: ['Press de banca', 'Press de pecho en polea', 'Flexiones', 'Pec deck', 'Press de pecho'] } },
  { categories: { en: 'Shoulders', de: 'Schultern', fr: 'Épaules', it: 'Spalle', es: 'Hombros' }, exercises: { en: ['Overhead Press', 'Dumbbell Shoulder Press', 'Lateral Raise', 'Face Pull'], de: ['Schulterdrücken', 'Schulterdrücken mit Kurzhanteln', 'Seitheben', 'Face Pull'], fr: ['Développé militaire', 'Développé épaules avec haltères', 'Élévations latérales', 'Face pull'], it: ['Lento avanti', 'Shoulder press con manubri', 'Alzate laterali', 'Face pull'], es: ['Press militar', 'Press de hombros con mancuernas', 'Elevaciones laterales', 'Face pull'] } },
  { categories: { en: 'Back', de: 'Rücken', fr: 'Dos', it: 'Schiena', es: 'Espalda' }, exercises: { en: ['Deadlift', 'Lat Pulldown', 'Pull-Up', 'Barbell Row', 'Rowing'], de: ['Kreuzheben', 'Latzug', 'Klimmzug', 'Langhantelrudern', 'Rudern'], fr: ['Soulevé de terre', 'Tirage vertical', 'Tractions', 'Rowing barre', 'Tirage horizontal'], it: ['Stacco da terra', 'Lat machine', 'Trazioni', 'Rematore con bilanciere', 'Rematore'], es: ['Peso muerto', 'Jalón al pecho', 'Dominadas', 'Remo con barra', 'Remo'] } },
  { categories: { en: 'Biceps', de: 'Bizeps', fr: 'Biceps', it: 'Bicipiti', es: 'Bíceps' }, exercises: { en: ['Barbell Curl', 'Dumbbell Curl', 'Hammer Curl', 'Concentration Curl'], de: ['Langhantelcurls', 'Kurzhantelcurls', 'Hammercurls', 'Konzentrationscurls'], fr: ['Curl barre', 'Curl haltères', 'Curl marteau', 'Curl concentré'], it: ['Curl con bilanciere', 'Curl con manubri', 'Curl a martello', 'Curl concentrato'], es: ['Curl con barra', 'Curl con mancuernas', 'Curl martillo', 'Curl de concentración'] } },
  { categories: { en: 'Triceps', de: 'Trizeps', fr: 'Triceps', it: 'Tricipiti', es: 'Tríceps' }, exercises: { en: ['Tricep Pushdown', 'Close-Grip Bench Press', 'Overhead Cable Extension', 'Bench Dip'], de: ['Trizepsdrücken', 'Enges Bankdrücken', 'Trizepsstrecken über Kopf am Kabel', 'Bank-Dips'], fr: ['Extension triceps à la poulie', 'Développé couché prise serrée', 'Extension triceps au-dessus de la tête', 'Dips sur banc'], it: ['Pushdown tricipiti', 'Panca a presa stretta', 'Estensione tricipiti sopra la testa', 'Dip su panca'], es: ['Extensión de tríceps en polea', 'Press de banca con agarre cerrado', 'Extensión de tríceps sobre la cabeza', 'Fondos en banco'] } },
  { categories: { en: 'Legs', de: 'Beine', fr: 'Jambes', it: 'Gambe', es: 'Piernas' }, exercises: { en: ['Squat', 'Leg Press', 'Leg Extension', 'Romanian Deadlift'], de: ['Kniebeuge', 'Beinpresse', 'Beinstrecken', 'Rumänisches Kreuzheben'], fr: ['Squat', 'Presse à cuisses', 'Extension des jambes', 'Soulevé de terre roumain'], it: ['Squat', 'Leg press', 'Leg extension', 'Stacco rumeno'], es: ['Sentadilla', 'Prensa de piernas', 'Extensión de piernas', 'Peso muerto rumano'] } },
  { categories: { en: 'Glutes', de: 'Gesäß', fr: 'Fessiers', it: 'Glutei', es: 'Glúteos' }, exercises: { en: ['Hip Thrust', 'Bulgarian Split Squat', 'Glute Bridge', 'Cable Glute Kickback'], de: ['Hip Thrust', 'Bulgarische Split Squats', 'Glute Bridge', 'Kabel-Kickbacks'], fr: ['Hip thrust', 'Fentes bulgares', 'Pont fessier', 'Extension fessiers à la poulie'], it: ['Hip thrust', 'Split squat bulgaro', 'Ponte per glutei', 'Calcio glutei ai cavi'], es: ['Hip thrust', 'Sentadilla búlgara', 'Puente de glúteos', 'Patada de glúteo en polea'] } },
  { categories: { en: 'Abs', de: 'Bauch', fr: 'Abdominaux', it: 'Addominali', es: 'Abdominales' }, exercises: { en: ['Plank', 'Cable Crunch', 'Hanging Leg Raise', 'Mountain Climbers'], de: ['Plank', 'Kabel-Crunch', 'Beinheben im Hang', 'Mountain Climbers'], fr: ['Planche', 'Crunch à la poulie', 'Relevé de jambes suspendu', 'Mountain climbers'], it: ['Plank', 'Crunch ai cavi', 'Sollevamento gambe alla sbarra', 'Mountain climber'], es: ['Plancha', 'Crunch en polea', 'Elevación de piernas colgado', 'Escaladores'] } },
  { categories: { en: 'Calves', de: 'Waden', fr: 'Mollets', it: 'Polpacci', es: 'Pantorrillas' }, exercises: { en: ['Standing Calf Raise', 'Seated Calf Raise'], de: ['Wadenheben im Stehen', 'Wadenheben im Sitzen'], fr: ['Mollets debout', 'Mollets assis'], it: ['Calf raise in piedi', 'Calf raise da seduto'], es: ['Elevación de talones de pie', 'Elevación de talones sentado'] } },
];
